repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-json
      - id: check-toml
      - id: check-yaml
      - id: detect-private-key
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0
    hooks:
      - id: mypy
        additional_dependencies:
          - types-PyYAML
  - repo: https://github.com/rhysd/actionlint
    rev: v1.7.1
    hooks:
      - id: actionlint-docker
  # TODO enable the hook
  # - repo: https://github.com/PyCQA/bandit
  #   rev: 1.7.9
  #   hooks:
  #     - id: bandit
  #       name: bandit (python)
  #       args: [--configfile, bandit.yaml, --severity-level, all]
  #       additional_dependencies: [bandit]
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        name: isort (python)
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.35.1
    hooks:
      - id: yamllint
        args: [--strict, -c=.yamllint]
  # TODO enable the hook
  # - repo: https://github.com/hadolint/hadolint
  #   rev: v2.13.0-beta
  #   hooks:
  #     - id: hadolint-docker
