type: function_sql
usage: chart(data, chart_type, ylabel)
description: |-
  Returns html with a chartjs chart
arguments:
  - name: data
    type: ARRAY<STRUCT<x STRING, y FLOAT64>>
  - name: chart_type
    type: STRING
  - name: ylabel
    type: STRING
output:
  name: html
  type: STRING
examples:
  - description: ""
    arguments:
      - "[('2022-08-01', 10000.), ('2022-08-02', 20000.), ('2022-08-03', 40000.), ('2022-08-04', 80000.)]"
      - "'bar'"
      - "'sales'"
    screenshot: chart.png
    region: ALL
code: |
  replace(replace(replace(replace(replace("""
    <div><canvas id="%ID%"></canvas></div>
    <script>
      (function() {
        new Chart(
          document.getElementById('%ID%'),
          {
              type: '%CHART_TYPE%',
              data: {
                labels: [%X%],
                datasets: [{
                  label: '%YLABEL%',
                  data: [%Y%],
                  borderColor: 'rgb(75, 192, 192)',
                  backgroundColor: 'rgb(75, 192, 192)',
                }]
              },
              options: {}
            }
        );
      })();
    </script>
  """,
  '%ID%', generate_uuid()),
  '%CHART_TYPE%', chart_type),
  '%YLABEL%', ylabel),
  '%X%', (select array_to_string(array_agg(format('"%s"', data.x) order by offset), ',') from unnest(data) data with offset as offset)),
  '%Y%', (select array_to_string(array_agg(cast(data.y as string) order by offset), ',') from unnest(data) data with offset as offset)
  )