type: function_sql
category: transform_array
author:
  name: Paul Marcombes
  url: https://www.linkedin.com/in/paul-marcombes
  avatar_url: "https://media-exp1.licdn.com/dms/image/C4E03AQF92ENRMYC3Mw/profile-displayphoto-shrink_800_800/0/1656924490995?e=1675900800&v=beta&t=Ertn0DSUvqzexmymI6NDba3TrXaSLRM_cQ5dxjmTkzo"
description: Return distinct values
arguments:
  - name: arr
    type: any type
output:
  name: distinct_values
  type: any type
examples:
  - description: ""
    arguments:
      - "[1, 4, 3, 4]"
    output: "[1, 4, 3]"
    region: ALL
code: array(select distinct value from unnest(arr) as value)
