type: function_sql
category: transform_array
author:
  name: Paul Marcombes
  url: https://www.linkedin.com/in/paul-marcombes
  avatar_url: "https://media-exp1.licdn.com/dms/image/C4E03AQF92ENRMYC3Mw/profile-displayphoto-shrink_800_800/0/1656924490995?e=1675900800&v=beta&t=Ertn0DSUvqzexmymI6NDba3TrXaSLRM_cQ5dxjmTkzo"
description: Return sorted array (descending)
arguments:
  - name: arr
    type: any type
output:
  name: sorted_array
  type: any type
examples:
  - description: ""
    arguments:
      - "[1, 4, 3]"
    output: "[4, 3, 1]"
    region: ALL
code: array(select value from unnest(arr) as value order by value desc)