type: function_sql
category: transform_array
author:
  name: "Benjamin Tabet"
  url: https://www.linkedin.com/in/benjamin-tabet
  avatar_url: "https://media-exp1.licdn.com/dms/image/C4D03AQGWnyJdEmZeZw/profile-displayphoto-shrink_400_400/0/1667928305931?e=1673481600&v=beta&t=sxH1fFMPjj9ASbqfQ6TkIpWKk_PQ0hUAhOtuAs2zTu0"
description: |-
  Return the sum of array values
arguments:
  - name: arr
    type: any type
output:
  name: value
  type: any type
examples:
  - description: ""
    arguments:
      - "[1, 4, 3]"
    output: "8"
    region: ALL
code: (select sum(value) from unnest(arr) value)
