name: Report a bug in a BigFunction
description: "Tell us what's wrong"
title: "[bug]: `function_name`: it does not work"
labels: ["bug-bigfunction"]
body:
  - type: markdown
    attributes:
      value: |
         ## 🙏 Thanks for taking the time to report a bug in a BigFunction! 
         
         Please fill the below fields to submit it.
  - type: checkboxes
    id: idea_does_not_exist
    attributes:
      label: Check the bug has not already been reported
      description: Check in [existing issues](https://github.com/unytics/bigfunctions/issues?q=is%3Aissue+is%3Aopen+label%3Abug-bigfunction) if your idea has not already been suggested. If it has, please don't create a new issue but add a comment on the existing one such as `+1` to upvote it. 
      options:
        - label: I could not find the bug in [existing issues](https://github.com/unytics/bigfunctions/issues?q=is%3Aissue+is%3Aopen+label%3Anew-bigfunction)
          required: true
  - type: checkboxes
    id: title_is_ok
    attributes:
      label: Edit `function_name` and the short error description in title above
      description: Edit the `function_name` and the short error description in the issue title above. 
      options:
        - label: I wrote the correct function name and a short error description in the title above
          required: true
  - type: textarea
    id: description
    attributes:
      label: What happened and what did you expect?
      description: Tell us what happened and what you expected. Please copy/past the exact queries that you made that created the bug and copy/paste the exact error text that you got. Don't hesitate to provide screenshots.
    validations:
      required: true
