type: function_js
author: Sid Ali
description: |
  Extract `values` from `json_string`
  which has only flat (no nested) key-values.
  Return `values` as an `array<string>`
arguments:
  - name: json_string
    type: string
output:
  name: values
  type: array<string>
examples:
  - description: ""
    arguments:
      - "'{\"created_at\": \"2022-01-01\", \"user\": \"sidali\"}'"
    output: "['2022-01-01', 'sidali']"
code: |
  try {
      obj = JSON.parse(json_string);
  }
  catch {
      throw('could not parse ' + json_string)
  }
  return Object.values(obj)
