type: function_sql
author: Paul Marcombes
description: Return sorted array (ascending)
arguments:
  - name: arr
    type: any type
output:
  name: sorted_array
  type: any type
examples:
  - description: ""
    arguments:
      - "[1, 4, 3]"
    output: "[1, 3, 4]"
code: array(select value from unnest(arr) as value order by value)
