name: deploy pages
on:
  push:
    branches:
      - master
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install -e .
      - run: bigfun docs generate --project bigfunctions --dataset eu,us,europe_west1,asia_east1
      - run: mkdocs gh-deploy --force
